const snapPapersData = {
  "2025": {
    "General English": [
      { id: "Q1", question: "Daniel Wheeler, at the head of his own table, was a charming host, and his ______ disappeared as the talk ran along on subjects grave or gay, but of no personal ______", options: ["A. gloom, potent", "B. cheer, intent", "C. melancholy, import", "D. joy, consequence"] },
      { id: "Q2", question: "Select the most appropriate antonym of PREPOSTEROUS:", options: ["A. Absurd", "B. Fantastic", "C. Insane", "D. Logical"] },
      { id: "Q3", question: "Fill in the blank: There is no such movie ______ you mention.", options: ["A. which", "B. that", "C. as", "D. who"] },
      { id: "Q4", question: "Grammatical error spot:\n(a) Even though every country has /\n(b) diverse sets of experience, I believe /\n(c) the global community can reach similar targets /\n(d) and common policies that deepen universal connection", options: ["A. (a)", "B. (b)", "C. (c)", "D. (d)"] },
      { id: "Q5", question: "Fill in the blanks: China's ultra-rich are ______ to make high-profile philanthropic donations to shore ______ their reputations...", options: ["A. enthusiastic, in", "B. competing, with", "C. working, off", "D. scrambling, up"] },
      { id: "Q6", question: "Identify Figure of Speech: 'It was claimed to be the most hi-tech train the country has ever seen but it got derailed in its first run.'", options: ["A. Hyperbole", "B. Irony", "C. Metaphor", "D. Paradox"] },
      { id: "Q7", question: "Match 'best' part of speech:\n1. Noun -> (iii) She can afford the best of everything.\n2. Adverb -> (i) You need to find out which program works best on your computer.\n3. Adjective -> (ii) At the wedding he'll be wearing his best suit.\n4. Verb -> (iv) My goal is to best the competition.", options: ["A. 1-(ii), 2-(i), 3-(iii), 4-(iv)", "B. 1-(iii), 2-(i), 3-(ii), 4-(iv)", "C. 1-(iii), 2-(iv), 3-(ii), 4-(i)", "D. 1-(i), 2-(iii), 3-(ii), 4-(iv)"] },
      { id: "Q8", question: "Idiom: Golden handshake", options: ["A. Shaking hands with golden gloves", "B. Good amount of money on early retirement", "C. Getting paid for doing nothing", "D. Cracking a good deal"] },
      { id: "Q9", question: "Compound word:", options: ["A. Hopscotch", "B. Frightened", "C. Acronym", "D. Trimester"] },
      { id: "Q10", question: "Incorrect phrasal verb usage:", options: ["A. The end product turned out okay in spite of the many production issues", "B. The judge issued an arrest warrant against the official who failed to turn up despite judicial summons", "C. You need to turn in the assignment by Monday", "D. I am going to turn myself in so that I can get up early. Good night!"] },
      { id: "Q11", question: "At a certain season of our life we are ______ to consider every spot as the possible site of a house. I have thus ______ the country on every side...", options: ["A. accustomed, observed", "B. habitual, surveyed", "C. adapted, travelled", "D. accustomed, surveyed"] },
      { id: "Q12", question: "Convert to Passive Voice: 'The mechanic remodelled the bike to help it sell at a high price.'", options: ["A. The bike has been remodelled by the mechanic to help it sell at a high price.", "B. The bike is remodelled by the mechanic to help it sell at a high price.", "C. The bike was sold at a high price by the mechanic after remodelling.", "D. The bike was remodelled by the mechanic to help it sell at a high price."] },
      { id: "Q13", question: "Parts of speech: The principal (1) of the school emphasized that the principal (2) reason for policy change was student safety.", options: ["A. adjective, adverb", "B. noun, adverb", "C. adjective, noun", "D. noun, adjective"] },
      { id: "Q14", question: "Fill in the blank: Last week, the central bank ______ all banks to provide a three-month moratorium...", options: ["A. asked", "B. order", "C. provided", "D. directed"] },
      { id: "Q15", question: "Correct spelling:", options: ["A. innosence", "B. indictment", "C. disastrus", "D. embarass"] }
    ],
    "Quantitative & Data Interpretation": [
      { id: "Q16", question: "Avg weight of 10 students = 30 kg. Include teacher A -> avg = 33 kg. Include teacher B -> avg = 34 kg. Weight of teacher B?", options: ["A. 45 kg", "B. 63 kg", "C. 70 kg", "D. 75 kg"] },
      { id: "Q17", question: "3/4 of A = 1/3 of B = 30% of C. Ratio A:B:C = ?", options: ["A. 4:8:9", "B. 6:9:10", "C. 4:9:10", "D. 4:9:12"] },
      { id: "Q18", question: "P sold watch to Q at ₹y. Q sold to R at 10% loss. R sold to T at 33.33% profit. T bought for ₹1176. Find (11/7) * y.", options: ["A. ₹1420", "B. ₹1860", "C. ₹1540", "D. ₹1280"] },
      { id: "Q19", question: "Smallest number divided by 16, 17, 20 leaving remainders 13, 14, 17.", options: ["A. 1357", "B. 1460", "C. 1268", "D. 1456"] },
      { id: "Q20", question: "If sin(θ) = 4/5, find (tan(θ) + 1)/(tan(θ) - 1).", options: ["A. 5", "B. 3", "C. 1", "D. 7"] },
      { id: "Q21", question: "Suman observes tree top across 40m wide river at 60°. Height of tree?", options: ["A. 20/√3", "B. 40√3", "C. 10√7", "D. 20√5"] },
      { id: "Q22", question: "Amount at end of 2nd and 3rd year at CI are ₹2640 and ₹2772. Rate of interest?", options: ["A. 6%", "B. 7%", "C. 5%", "D. 4%"] },
      { id: "Q23", question: "Votes: P=300, Q=250, R=200, S=150, T=100. Ratio of 2 highest polling to 2 lowest polling?", options: ["A. 5:11", "B. 11:5", "C. 5:2", "D. 2:5"] },
      { id: "Q24", question: "If log_n(75) = p and log_n(45) = q, log_n(15) = ?", options: ["A. (p+q)/3", "B. (p+q)/2", "C. (2p+2q)/3", "D. (3p+3q)/2"] },
      { id: "Q25", question: "Value of log(2) + log(4) + log(8) + ... + log(2^n) where log(2) = x:", options: ["A. n(n+1)x / 2", "B. n(n+1)(2n+1)x / 6", "C. nx", "D. n(n+1)x"] },
      { id: "Q26", question: "Class of 60: 40 passed English, 45 passed Computers, 5 failed both. Passed both?", options: ["A. 22", "B. 30", "C. 24", "D. 25"] },
      { id: "Q27", question: "Probability vowels appear together in permutations of 'COMPUTER':", options: ["A. 3/168", "B. 5/84", "C. 3/84", "D. 3/28"] },
      { id: "Q28", question: "400m race: A beats B by 40m, C by 80m. In 200m race, B beats C by?", options: ["A. 20 metres", "B. 22.22 metres", "C. 18.88 metres", "D. 23.33 metres"] },
      { id: "Q29", question: "A, B, C complete project in n days. Together take (1/5)th time A alone takes, or (2/3)rd time B alone takes. Time C alone takes?", options: ["A. 10n days", "B. 5n/2 days", "C. 8n days", "D. 15n/2 days"] },
      { id: "Q30", question: "Sum to infinity: 6/(2*3*4) + 7/(3*4*5) + 8/(4*5*6) + ...", options: ["A. 1/2", "B. 4/5", "C. 2/3", "D. 3/4"] },
      { id: "Q31", question: "Bulbs: 40% blue, 20% green, 40% red. 30% red defective. Overall 24% defective. 80% blue non-defective. If defective blue = 120, non-defective green = ?", options: ["A. 60", "B. 120", "C. 240", "D. 360"] },
      { id: "Q32", question: "23 pens + 60 pencils + 28 erasers = ₹2530. 17 pens + 44 pencils + 21 erasers = ₹1890. Cost of 4 pens + 16 pencils?", options: ["A. 80", "B. 120", "C. 160", "D. Cannot be determined"] },
      { id: "Q33", question: "System of equations has NO solution:\n9ax + 2y = 3\n4x + (2-a)y = 2\nCondition:", options: ["A. 3a - 4 = 0", "B. 3a - 2 = 0", "C. 3a + 2 = 0", "D. 3a + 4 = 0"] },
      { id: "Q34", question: "Probability that a 3-digit palindrome number is divisible by 9?", options: ["A. 1/10", "B. 1/9", "C. 1/8", "D. 1/7"] },
      { id: "Q35", question: "2 dice rolled: Probability sum is prime AND at least one individual roll is prime?", options: ["A. 5/18", "B. 1/3", "C. 11/36", "D. 1/4"] }
    ],
    "Analytical & Logical Reasoning": [
      { id: "Q36", question: "Missing number:\n8 | 24 | 12\n7 | ?  | 24\n9 | 45 | 32", options: ["A. 42", "B. 36", "C. 37", "D. 32"] },
      { id: "Q37", question: "Replace ?: 17, 24, 32, 38, ?", options: ["A. 46", "B. 62", "C. 70", "D. 68"] },
      { id: "Q38", question: "Replace ?: B, C, E, G, K, M, ?", options: ["A. P", "B. O", "C. Q", "D. S"] },
      { id: "Q39", question: "Praise : Criticism :: Urge : ?", options: ["A. Force", "B. Request", "C. Deter", "D. Increase"] },
      { id: "Q40", question: "Meaningful order: 1. Write, 2. Read, 3. Choosing topic, 4. Publish, 5. Format", options: ["A. 3, 5, 4, 1, 2", "B. 3, 5, 1, 4, 2", "C. 3, 4, 1, 5, 2", "D. 3, 1, 5, 4, 2"] },
      { id: "Q41", question: "Odd one out:", options: ["A. (16, 24, 42)", "B. (34, 81, 61)", "C. (14, 23, 25)", "D. (18, 72, 81)"] },
      { id: "Q42", question: "Queue of 30 boys: 22 in front of Kunal, 12 behind Rohit. Boys between Kunal and Rohit?", options: ["A. 3", "B. 4", "C. 6", "D. 5"] },
      { id: "Q43", question: "Defective keyboard: A -> ABCA, B -> BACB, C -> ABCB. Typed 48 letter sequence: ABCCBAABCCBA... 100th character on screen?", options: ["A. A", "B. B", "C. C", "D. cannot be determined"] },
      { id: "Q44", question: "Floor arrangement: A & E live on even floors. C above them. D above C. F not on bottom floor. B on remaining floor. Who lives on floor 3?", options: ["A. B", "B. C", "C. D", "D. F"] },
      { id: "Q45", question: "Using same arrangement as Q44, who lives on floor 5?", options: ["A. D", "B. C", "C. F", "D. B"] },
      { id: "Q46", question: "'He is the only son of only daughter of my grandfather.' How is Ram related to man in photograph?", options: ["A. Brother", "B. Cousin", "C. Brother-in-law", "D. Can't be determined"] },
      { id: "Q47", question: "'Kawan's grandson is the only son of my sister.' How is Kawan related to Sheena (if Kawan has a wife)?", options: ["A. Father", "B. Father-in-law", "C. Uncle", "D. Cannot be determined"] },
      { id: "Q48", question: "1st Jan 2000 was Saturday. First Monday in August 2005 falls on?", options: ["A. 1st", "B. 4th", "C. 3rd", "D. 6th"] },
      { id: "Q49", question: "Time between 7 and 8 o'clock hands in same straight line but opposite?", options: ["A. 5(5/11) past 7", "B. 4(5/11) past 7", "C. 5(4/11) past 7", "D. 5(3/11) past 7"] },
      { id: "Q50", question: "15 June 2007 was Sunday. Day on 14 July 2009?", options: ["A. Tuesday", "B. Friday", "C. Monday", "D. Thursday"] },
      { id: "Q51", question: "Statements: All phones are desktops. All computers are televisions. No desktop is a computer.\nConclusions: I. Some televisions can be phones. II. No computer is a phone.", options: ["A. Only I", "B. Only II", "C. Neither", "D. Both I and II"] },
      { id: "Q52", question: "3 friends know other two's result. Teacher says 'At least one failed'. None knew own result after statement.", options: ["A. One student failed.", "B. Two students failed.", "C. Two or more students failed.", "D. All three failed."] },
      { id: "Q53", question: "Increase GDP by 40% to avoid economic collapse. Once 40% reached, 50% is easy. Which is true?", options: ["A. Economy fails if not able to increase by 50%", "B. GDP 50% increase if economy fails", "C. Economy will not fail if it can increase economy by 50%", "D. 10% increase not possible even after 40%"] },
      { id: "Q54", question: "Weaken argument: 'Jadeja is bad batsman because he scored least on recent tour.'", options: ["A. Exceptional bowling/fielding", "B. Started as bowler", "C. Played with experimental heavy bat by captain's order", "D. Top scorer 2 years ago"] },
      { id: "Q55", question: "Course of action: Foreign national killed by uncontacted tribe after trespassing prohibited island.", options: ["A. Issue public apology and ensure no recurrence", "B. Arrest tribal people", "C. Explain foreign national was at fault for trespassing", "D. Conduct awareness camps for tribe"] },
      { id: "Q56", question: "Assumption: Prevent tick infestation by keeping plumbing in good condition.", options: ["A. Ticks cannot be filtered from air", "B. House owners know plumbing", "C. Ticks cannot grow in dry areas", "D. Ticks do not cause moisture"] },
      { id: "Q57", question: "Flaw in manager's plan: Rejecting exactly 50/200 shoes weekly to maintain standard assumes:", options: ["A. Cannot accept all shoes", "B. Quality won't improve if production reduced", "C. Each shoe reviewed is worthy", "D. The 150 accepted shoes will be of same quality week to week"] },
      { id: "Q58", question: "Beas reserve passage on Indus river dolphins. Conclusion:", options: ["A. No human movement -> better water quality", "B. Good water quality -> higher spotting of aquatic life", "C. Dolphins rarest mammals, seen more if clean water", "D. All of the above"] },
      { id: "Q59", question: "Statement: Children without proper care suffer malnutrition.\nConclusions: I. Malnutrition child deaths on rise since 2000. II. All malnourished children lacked care.", options: ["A. Only I", "B. Only II", "C. Both", "D. Neither"] },
      { id: "Q60", question: "Statements: African countries face population rise & resource depletion.\nConclusions: I. Developing countries face similar problem today. II. Governments will struggle to provide quality of life.", options: ["A. Only I", "B. Only II", "C. Neither", "D. Both"] }
    ]
  },
  "2024": {
    "General English": [
      { id: "Q1", question: "Sentence Rearrangement:\nS1: The library is a place where knowledge is preserved and shared with all.\nP: Students and researchers often visit to find useful information for their studies.\nQ: It houses thousands of books, journals, and digital resources on various subjects.\nR: The peaceful environment helps visitors focus and absorb knowledge effectively.\nS: Librarians play a crucial role in organizing and maintaining these resources.\nS6: Thus, the library serves as a treasure trove of wisdom for generations.", options: ["(a) RSQP", "(b) PQRS", "(c) SQPR", "(d) QSPR"] },
      { id: "Q2", question: "Idiom Meaning: 'To burn the midnight oil'", options: ["(a) To waste time", "(b) To work late into the night", "(c) To celebrate all night", "(d) To sleep early"] },
      { id: "Q3", question: "Idiom Meaning: 'Hit the nail on the head'", options: ["(a) To make a mistake", "(b) To be very precise or accurate", "(c) To get hurt while working", "(d) To start an argument"] },
      { id: "Q4", question: "Opposite word of ARDENT:", options: ["(a) Indifferent", "(b) Zealous", "(c) Fervent", "(d) Enthusiastic"] },
      { id: "Q5", question: "Indirect Speech: She said, 'I have completed my assignment on time.'", options: ["(a) She said that she had completed her assignment on time.", "(b) She said that I have completed my assignment on time.", "(c) She said that she completed her assignment on time.", "(d) None of these"] },
      { id: "Q6", question: "Direct Speech: The teacher told the students that the Earth revolves around the Sun.", options: ["(a) The teacher said, 'The Earth revolved around the Sun.'", "(b) The teacher said, 'The Earth revolves around the Sun.'", "(c) The teacher said, 'The Earth is revolving around the Sun.'", "(d) The teacher said, 'The Earth had revolved around the Sun.'"] },
      { id: "Q7", question: "Sentence completion: Even though she was unwell, .......", options: ["(a) she continued working with determination.", "(b) she decided to go on a long vacation.", "(c) she avoided taking any rest at all.", "(d) she stopped working immediately."] },
      { id: "Q8", question: "Sentence completion: The moment the fire alarm rang, .......", options: ["(a) everyone ignored it and continued their work.", "(b) people evacuated the building immediately.", "(c) the fire brigade arrived instantly.", "(d) the fire alarm stopped ringing."] },
      { id: "Q9", question: "Sentence completion: If we don't leave now, ......", options: ["(a) we will reach the destination early.", "(b) we might miss the train.", "(c) we will have plenty of time to spare.", "(d) we will arrive much before schedule."] },
      { id: "Q10", question: "Synonym of BENEVOLENT:", options: ["(a) kind", "(b) cruel", "(c) selfish", "(d) hostile"] },
      { id: "Q11", question: "Correctly spelt word:", options: ["(a) Artifact", "(b) Artifect", "(c) Arttefect", "(d) Arrtefact"] },
      { id: "Q12", question: "Fill in the blank: The manager's decision to fire the employee was seen as a ______ act of revenge rather than a professional choice.", options: ["(a) vindictive", "(b) malicious", "(c) spiteful", "(d) callous"] },
      { id: "Q13", question: "Fill in the blank: Despite his repeated failures, the entrepreneur remained ______ in his pursuit of success.", options: ["(a) obstinate", "(b) resolute", "(c) relentless", "(d) unwavering"] },
      { id: "Q14", question: "Analogy: FLORIST : FLOWERS ::", options: ["(a) Chef : Food", "(b) Author : Books", "(c) Painter : Canvas", "(d) None of these"] },
      { id: "Q15", question: "Analogy: SENTINEL : WATCH ::", options: ["(a) Artist : Paint", "(b) Soldier : Battle", "(c) Guard : Protect", "(d) None of these"] }
    ],
    "Quantitative & Data Interpretation": [
      { id: "Q16", question: "On a certain principal, CI and SI for 2 years are ₹16,560 and ₹14,400 respectively. Find principal and rate per annum.", options: ["(a) 216,000, 13%", "(b) 20,000, 30%", "(c) 24,000, 30%", "(d) 24,000, 35%"] },
      { id: "Q17", question: "x + y + z = 850. If x - 100, y - 25, z - 50, then x:y = 1:2, y:z = 5:6. Find original x + y.", options: ["(a) 400", "(b) 500", "(c) 550", "(d) 350"] },
      { id: "Q18", question: "Find value of log(87600) + log(23100) - 8 = ?", options: ["(a) log(8.76) + log(2.31)", "(b) log(87.6) + log(23.1)", "(c) log(876) + log(231)", "(d) None of these"] },
      { id: "Q19", question: "Ravi's avg expenditure Jan-Jun is ₹3200. Jul: ₹3000, Aug: ₹3600, Sep: ₹3900, Oct: ₹4200. Nov expenditure is 50% of Dec. Overall avg is ₹3200. Nov expenditure?", options: ["(a) 1600", "(b) 1400", "(c) 1700", "(d) 1500"] },
      { id: "Q20", question: "Ram and Shyam are 10 km apart. See balloon at angles 60° and 30°. Balloon height?", options: ["(a) 4√3", "(b) 5√3", "(c) 3√3", "(d) 2√3"] },
      { id: "Q21", question: "Manufacturer makes 1500 articles at 120 paisa/article. SP fixed so selling 1200 gives 80% profit on outlay. 240 spoilt, remaining sold at this SP. Actual profit %?", options: ["(a) 84", "(b) 82", "(c) 89", "(d) 86"] },
      { id: "Q22", question: "Find missing number 'x':\nRow 1: 30, 102 -> 3050\nRow 2: 5, 8 -> 30\nRow 3: 5, 3 -> 5\nRow 4: 8, x -> 102", options: ["(a) 14", "(b) 12", "(c) None of these", "(d) 10"] },
      { id: "Q23", question: "Box contains 3 red, 3 blue, 7 green marbles. Pick 2 randomly. Probability both are non-green?", options: ["(a) 3/26", "(b) 5/26", "(c) 9/26", "(d) 7/26"] },
      { id: "Q24", question: "₹45,000 deposited for 4 years CI. Interest rate: 6% 1st yr, increases 1% every year. Approx amount at end of 4 yrs?", options: ["(a) 60,000", "(b) 70,000", "(c) 80,000", "(d) 90,000"] },
      { id: "Q25", question: "Shopkeeper marks 30% above CP, gives 15% discount. Uses faulty weight 1kg for 800g. Actual profit %?", options: ["(a) 38.125%", "(b) 24.425%", "(c) 32.124%", "(d) None of these"] },
      { id: "Q26", question: "Trapezium ABCD (AB || CD). ∠ABC=90°, ∠BAD=45°. CD=5cm, BC=4cm. Area?", options: ["(a) 20 cm²", "(b) None of these", "(c) 28 cm²", "(d) 24 cm²"] },
      { id: "Q27", question: "School application problem: If 100 fewer applied and 50 fewer selected, ratio selected:unselected becomes 7:4. Original ratio 3:2. How many applied originally?", options: ["(a) 325", "(b) 415", "(c) 375", "(d) 425"] },
      { id: "Q28", question: "Smallest number between 2000 and 3000 divisible by 21, 24, 28.", options: ["(a) None of these", "(b) 2000", "(c) 2352", "(d) 2016"] },
      { id: "Q29", question: "Next term: 5, 6, 16, 57, 244, 1245, ?", options: ["(a) 7506", "(b) None of these", "(c) 5500", "(d) 4047"] },
      { id: "Q30", question: "Rice weights: 435, 493, 551 kg. Packed in equal size bags without mixing. Least number of bags?", options: ["(a) 51", "(b) 56", "(c) 57", "(d) 54"] },
      { id: "Q31", question: "₹776 divided among 300 boys and girls. Boy gets ₹2.40, girl gets ₹2.80. Total girls?", options: ["(a) 130", "(b) 140", "(c) 110", "(d) 120"] },
      { id: "Q32", question: "Square root of 4^(6x²) * 25^(y/2) * 9^(z⁴):", options: ["(a) 4^(3x²) * 5^y * 3^(z⁴)", "(b) 4^(3x²) * 5^(y/2) * 9^(x²)", "(c) 4^(6x) * 25^(y/4) * 9^(x²)", "(d) 4^(3x²) * 5^(y/2) * 3^(z⁴)"] },
      { id: "Q33", question: "Which year has lowest percentage fall in imports from previous year?", options: ["(a) 2021", "(b) 2024", "(c) 2023", "(d) 2020"] },
      { id: "Q34", question: "2 oranges + 3 bananas + 4 apples = ₹15. 3 oranges + 2 bananas + 1 apple = ₹10. Cost of 3 oranges + 3 bananas + 3 apples?", options: ["(a) ₹10", "(b) ₹8", "(c) Cannot be determined", "(d) ₹15"] },
      { id: "Q35", question: "Equal glasses with alcohol:water ratios 2:1 and 1:1 emptied into third glass. Final ratio?", options: ["(a) 5:7", "(b) 7:5", "(c) 7:6", "(d) 6:7"] }
    ],
    "Analytical & Logical Reasoning": [
      { id: "Q36", question: "If 2nd October is Monday, 2nd November is:", options: ["(a) Friday", "(b) Tuesday", "(c) Thursday", "(d) Wednesday"] },
      { id: "Q37", question: "Three thieves M, B, V. Only 1 tells truth.\nM: I am innocent\nB: I am innocent\nV: B is involved in robbery\nWho was involved?", options: ["(a) M", "(b) B", "(c) V", "(d) Cannot be determined"] },
      { id: "Q38", question: "Clock set right Monday 3:00 AM, gains 2 mins/hr. Time in clock when actual time is 7:30 PM Tuesday?", options: ["(a) 8:48 PM", "(b) 8:45 PM", "(c) 8:51 PM", "(d) 9:10 PM"] },
      { id: "Q39", question: "Missing code: L1#1O2-2, J2#2Q3-3, _______, F4#4U5-5, D5#5W6-6", options: ["(a) H3#3T4-4", "(b) None of these", "(c) H3#3S4-4", "(d) E3#3V4-4"] },
      { id: "Q40", question: "A introduces B: 'She is the wife of the grandson of father of my father'. B to A?", options: ["(a) Sister-in-law", "(b) Daughter", "(c) Sister", "(d) Mother"] },
      { id: "Q41", question: "Narmada Bachao Andolan : Medha Patkar :: Bhudan Andolan : ?", options: ["(a) Vinoba Bhave", "(b) Kailash Satyarthi", "(c) None of these", "(d) Jawahar Lal Nehru"] },
      { id: "Q42", question: "Complete series: 14, 26, 36, 44, 50, _____", options: ["(a) 54", "(b) None", "(c) 48", "(d) 52"] },
      { id: "Q43", question: "Statement: Office notice to mark online facial recognition attendance.\nAssumptions: 1. Notice will be read. 2. Online attendance benefits company.", options: ["(a) Only 1", "(b) Only 2", "(c) Neither", "(d) Both"] },
      { id: "Q44", question: "Earthquake in ocean -> Tsunami -> 192 deaths & $7M loss. Identify effects:", options: ["(a) Death, Tsunami Wave, Property loss", "(b) Damage House, Tsunami Wave, Property loss", "(c) Casualties, Prop Loss, Death", "(d) Tectonic Movement, Death, Earthquake"] },
      { id: "Q45", question: "Statements: Some M are L. All H are W. Some W are M.\nConclusions: I. All M are W II. Some H are L III. Some W are H", options: ["(a) None of the statements", "(b) I & III", "(c) Only III", "(d) Only I"] },
      { id: "Q46", question: "Angle between clock hands at 5:55 PM:", options: ["(a) 150°", "(b) 152.5°", "(c) 155.5°", "(d) 125.5°"] },
      { id: "Q47", question: "If 9th Dec 2007 is Sunday, 8th July 2007 was:", options: ["(a) Tuesday", "(b) Thursday", "(c) Friday", "(d) Saturday"] },
      { id: "Q48", question: "Cuckoo strikes at regular intervals, takes 10s to strike at 6 o'clock. Seconds to strike at 10 o'clock?", options: ["(a) 10 seconds", "(b) 15 seconds", "(c) 16.7 seconds", "(d) 16 seconds"] },
      { id: "Q49", question: "Adhir Mishra has children: Urmila, Raghu, Sumit. Sumit married Roma (eldest daughter of Mohans). How is Mrs. Mohan related to Sumit?", options: ["(a) Aunt", "(b) Mother-in-law", "(c) Mother", "(d) Sister-in-law"] },
      { id: "Q50", question: "Surname of Sohan (son of Sumit and Roma)?", options: ["(a) Sharma", "(b) Mohan", "(c) Mishra", "(d) Raghu"] },
      { id: "Q51", question: "Raj walks X to Y (80m), turns right (50m), turns right (70m), turns right (50m). Distance from start?", options: ["(a) 10 metres", "(b) 20 metres", "(c) 50 metres", "(d) 70 metres"] },
      { id: "Q52", question: "5 friends (Keshav, Rekha, Parul, Megha, Nikku). Arranged descending by age, 3rd position?", options: ["(a) Parul", "(b) Keshav", "(c) Nikku", "(d) None of these"] },
      { id: "Q53", question: "Using same group as Q52, arranged ascending by height, 4th position?", options: ["(a) Nikku", "(b) Parul", "(c) Rekha", "(d) Keshav"] },
      { id: "Q54", question: "Meaningful word from 2nd, 5th, 8th letters of 'CARETAKER':", options: ["(a) A", "(b) E", "(c) X", "(d) M"] },
      { id: "Q55", question: "Venn diagram: Triangle(small)=teachers, Triangle(big)=politicians, Circle=graduates, Rectangle=MP. Graduates or teachers but NOT politicians:", options: ["(a) B, G", "(b) G, H", "(c) A, E", "(d) E, F"] },
      { id: "Q56", question: "Graduate politicians but NOT MP:", options: ["(a) B, C", "(b) L, B", "(c) D, L", "(d) A, H, L"] },
      { id: "Q57", question: "Statements: 'All sweet things are fluids', 'Some fluids are coloured things'. Implies:\nA. Some sweet things are coloured\nB. Some sweet things are fluids\nC. All fluids are sweet\nD. Some fluids are sweet", options: ["(a) A, B and C only", "(b) A and C only", "(c) B, C and D only", "(d) A, C and D only"] },
      { id: "Q58", question: "Four trees (Lemon, Coconut, Mango, Neem) at corners. Well & Cabin at opposite corners. Lemon & Coconut on sides of gate opposite Well/Cabin side. Diagonally opposite pair?", options: ["(a) Cabin and Neem tree", "(b) Coconut tree and Lemon tree", "(c) Mango tree and Well", "(d) Neem tree and Lemon tree"] },
      { id: "Q59", question: "Missing pattern: B2CD, DE3F, _______, H5IJ, J6KL", options: ["(a) G3HI", "(b) FG4H", "(c) D3GH", "(d) FGH4"] },
      { id: "Q60", question: "Rearrange 1-R, 2-A, 3-C, 4-E, 5-T to form meaningful word:", options: ["(a) 1, 2, 3, 4, 5", "(b) 3, 2, 1, 4, 5", "(c) 5, 2, 3, 4, 1", "(d) 5, 1, 2, 3, 4"] }
    ]
  },
  "2023": {
    "General English": [
      { id: "Q1", question: "The proverb 'A rolling stone gathers no moss' emphasizes that:", options: ["(a) One should be content with what they have and avoid change.", "(b) Patience and perseverance are key to achieving success.", "(c) Frequent movement leads to a lack of progress.", "(d) New experiences bring valuable knowledge and growth."] },
      { id: "Q2", question: "In the following question, a sentence is given with a phrasal verb in bold. Choose the correct phrasal verb: She narrowed the exam down in the first attempt.", options: ["(a) opted for", "(b) nailed down", "(c) passed out", "(d) No Error"] },
      { id: "Q3", question: "Out of the four options given, select the most logical order of the sentences to form a coherent paragraph.\nP: When the game of life is finally over there is no second chance to correct our errors.\nQ: Time is the greater equalizer of all mankind.\nR: Time offers opportunity but demands a sense of regard.\nS: It has taken away the best and the worst of us without regard of either.", options: ["(a) QSRP", "(b) RSQP", "(c) QRSP", "(d) RSPQ"] },
      { id: "Q4", question: "Convert into Active/Passive Voice: You can play with these kittens quite safely.", options: ["(a) These kittens can played with quite safely.", "(b) These kittens can play with you quite safely.", "(c) These kittens can be played with you quite safely.", "(d) These kittens can be played with quite safely."] },
      { id: "Q5", question: "The speaker describes their overwhelming workload as a _____ drowning them in tasks.", options: ["(a) Rushing river", "(b) Gentle breeze", "(c) Sparkling fountain", "(d) Heavy stone"] },
      { id: "Q6", question: "Error spot: If I was you, (a)/ I would not allow them (b)/ such leverage in the business.(c)/ No error(d)", options: ["(a)", "(b)", "(c)", "(d)"] },
      { id: "Q7", question: "Opposite meaning of treacherous:", options: ["(a) perilous", "(b) mutinous", "(c) seditious", "(d) secure"] },
      { id: "Q8", question: "Meaning of exemplary:", options: ["(a) flawed", "(b) faulty", "(c) ideal", "(d) boisterous"] },
      { id: "Q9", question: "Fill in the preposition: We must mail the letter _____ Friday.", options: ["(a) by", "(b) since", "(c) until", "(d) for"] },
      { id: "Q10", question: "Question tag: I guess he is in a hurry, _____?", options: ["(a) doesn't he", "(b) is he", "(c) isn't he", "(d) does he"] },
      { id: "Q11", question: "The librarian asked everyone to be more _____ as she needed silence to concentrate on filing the new books.", options: ["(a) respectful", "(b) enthusiastic", "(c) confused", "(d) talkative"] },
      { id: "Q12", question: "Having _____ the report all night, Sarah was exhausted but satisfied with the final product.", options: ["(a) written", "(b) write", "(c) to write", "(d) writes"] },
      { id: "Q13", question: "Correct spelling of penacea:", options: ["(a) panacea", "(b) penecea", "(c) panacia", "(d) panacya"] },
      { id: "Q14", question: "_____ my best friend Hasan is five years older than me, he looks very young.", options: ["(a) Until", "(b) When", "(c) Although", "(d) Because"] },
      { id: "Q15", question: "After a _____ three months of stock market activity, the price of bonds _____ last week.", options: ["(a) tumultuous, stabilised", "(b) hectic, fell", "(c) variety, surged", "(d) continuous, soared"] }
    ],
    "Quantitative & Data Interpretation": [
      { id: "Q16", question: "Roy bought articles at Rs 20 per item. He sells them for Rs 2, Rs 4 and Rs 6 and so on. He intends to make at least a profit of 40%. What will be the minimum number of articles he should sell?", options: ["(a) 25", "(b) 27", "(c) 28", "(d) None of these"] },
      { id: "Q17", question: "A and B have bags full of one rupee coins. Total value is Rs 45. 5 coins dropped from each bag due to holes. Product of remaining coins is 124. Find the product of initial coins.", options: ["(a) 350", "(b) 324", "(c) 200", "(d) None of these"] },
      { id: "Q18", question: "Imran sold a mobile phone for Rs. 17600 after 12% discount on marked price, earning 10% profit. Find profit % if no discount is given?", options: ["(a) 12%", "(b) 22%", "(c) 25%", "(d) None of these"] },
      { id: "Q19", question: "160 persons (male/female) participated in an event. 1240 apples distributed. Each male gets 7 apples and each female gets 12 apples. Find number of females.", options: ["(a) 24", "(b) 26", "(c) 28", "(d) 30"] },
      { id: "Q20", question: "Mixture contains 3/4 milk and 1/4 water. Diluted with water to contain 1/2 milk and 1/2 water. How much liquid is extracted and replaced with water?", options: ["(a) 1/2", "(b) 1/4", "(c) 1/3", "(d) None of these"] },
      { id: "Q21", question: "Shopkeeper mixes two types of sugar. Mixed in 3:2, profit is 10%. Mixed in 2:3, profit is 5%. Selling price is Rs 40. Find ratio of cost prices.", options: ["(a) 2:3", "(b) 19:24", "(c) 17:20", "(d) None of these"] },
      { id: "Q22", question: "4 different positive numbers in ascending order. 1/4th of average of all 4 is 24 less than the greatest. If average of first 3 is 32, greatest number is:", options: ["(a) 32", "(b) 34", "(c) 36", "(d) None of these"] },
      { id: "Q23", question: "A and B complete work in 2 days (5 hrs/day). B and C in 4 days (6 hrs/day). C and A in 2 days (6 hrs/day). How many days for A alone at 5 hrs/day?", options: ["(a) 3", "(b) 5", "(c) 12", "(d) 15"] },
      { id: "Q24", question: "Sonu, Monu and Romu scored 342 runs in total. Sonu:Monu = 3:2, Monu:Romu = 3:2. Find runs scored by Romu.", options: ["(a) 96", "(b) 64", "(c) 72", "(d) None of these"] },
      { id: "Q25", question: "Letters of MINUTE arranged such that vowels occupy only odd positions.", options: ["(a) 32", "(b) 36", "(c) 48", "(d) None of these"] },
      { id: "Q26", question: "Ways to distribute 7 different chocolates to A, B, C such that at least one gets exactly one chocolate?", options: ["(a) 1050", "(b) 1176", "(c) 1218", "(d) None of these"] },
      { id: "Q27", question: "Group X (3G, 2B) chosen if die shows 1. Group Y (3G, 4B) chosen if 2 or 3. Group Z (4G, 5B) chosen if 4, 5, 6. If a girl is chosen, probability she is from group Y?", options: ["(a) 7/90", "(b) 63/293", "(c) 90/293", "(d) None of these"] },
      { id: "Q28", question: "Mohini speaks truth 6/9 times, Rohini 3/6 times. Probability they contradict each other?", options: ["(a) 1/2", "(b) 2/3", "(c) 4/5", "(d) None of these"] },
      { id: "Q29", question: "x, y, z are consecutive numbers and log(1+xz) = 2A, find A.", options: ["(a) log x", "(b) log y", "(c) log z", "(d) None of these"] },
      { id: "Q30", question: "Decreasing AP, sum except 1st term is -75, sum of all terms is 0. Difference between 9th and 13th term is 20. Find 1st term.", options: ["(a) 25", "(b) 30", "(c) 35", "(d) None of these"] },
      { id: "Q31", question: "Equilateral triangle area 240 sq units. Corners cut to form regular hexagon. Area of hexagon:", options: ["(a) 120", "(b) 160", "(c) 180", "(d) None of these"] },
      { id: "Q32", question: "Flower bed areas: 125, 375, 250 sq m. Maximum rows of flowers if row width is 3 sq m?", options: ["(a) 249", "(b) 246", "(c) 250", "(d) None of these"] },
      { id: "Q33", question: "Point observes top of building at 30°. Moves 500m towards building, angle becomes 75°. Height of building?", options: ["(a) 125(√3+1)", "(b) 250(√3+1)", "(c) 500(√3+1)", "(d) None of these"] },
      { id: "Q34", question: "Male population above Edu Index for UP is 1.6 lakhs. Total UP population in lakhs (approx)?", options: ["(a) 2.28", "(b) 2.96", "(c) 3.67", "(d) 3.69"] },
      { id: "Q35", question: "3+2=7, 51+7=76, 32-8=-32, 12+3=21. Value of '?' in 51+(?)=76:", options: ["(a) 7", "(b) 25", "(c) 5", "(d) None of these"] }
    ],
    "Analytical & Logical Reasoning": [
      { id: "Q36", question: "Next term: 1, 3, 7, 13, 21, 31, _____", options: ["(a) 67", "(b) 43", "(c) 31", "(d) 52"] },
      { id: "Q37", question: "Next term: Tue, Wed, Fri, Mon, ?, Wed", options: ["(a) Wed", "(b) Fri", "(c) Thu", "(d) Sat"] },
      { id: "Q38", question: "If 8055 & 238945 = BOSS and ZEBRAS, then LEETS = ?", options: ["(a) 23375", "(b) 13357", "(c) 13572", "(d) 13375"] },
      { id: "Q39", question: "Suresh bhai (father-in-law of Mahesh's wife) has 1 son. Brother-in-law of Mahesh is Paresh & Suresh is Ramesh's Grandfather. Mahesh has no Sister-in-law. Paresh to Ramesh?", options: ["(a) 21534", "(b) 21354", "(c) 21543", "(d) Maternal Uncle"] },
      { id: "Q40", question: "Logical sequence: 1. Pune 2. Aga Khan Palace 3. World 4. India 5. Maharashtra", options: ["(a) 21534", "(b) 21354", "(c) 21543", "(d) 15425"] },
      { id: "Q41", question: "In 24h clock, [(angle P at 6:00) + (angle P at 18:00)] / (angle P at 12:00) = ?", options: ["(a) 3", "(b) 2", "(c) 4", "(d) None of these"] },
      { id: "Q42", question: "Mohini speaks truth 6/9, Rohini 3/6. Probability of contradiction?", options: ["(a) 1/2", "(b) 4/5", "(c) 2/3", "(d) None"] },
      { id: "Q43", question: "Complete series: 15, 21, 27, 33, 35, 39, _____, 51, 55", options: ["(a) 47", "(b) 49", "(c) 45", "(d) 50"] },
      { id: "Q44", question: "Arrange bottom to top: 1. Knees 2. Elbow 3. Head 4. Tongue 5. Neck 6. Foot", options: ["(a) 345216", "(b) 345261", "(c) 345621", "(d) None of these (Correct: 6, 1, 2, 5, 4, 3)"] },
      { id: "Q45", question: "Calendar repetition of 2003:", options: ["(a) 2032", "(b) 2034", "(c) 2025", "(d) 2028"] },
      { id: "Q46", question: "Statements: Only a few Chocolate are Table. Only a few Tables are Plants. Only a few Plants are Fan.\nConclusions: I. Some fan is Chocolate is a possibility. II. All fan are Tables.", options: ["(a) Only I", "(b) Only II", "(c) Either", "(d) Neither"] },
      { id: "Q47", question: "Statements: Only a few Ant are Cow. No cow is Joker. Only a few Joker are Deer.\nConclusions: I. Some Ant are Joker. II. Some Deer are Ant.", options: ["(a) Only I", "(b) Only II", "(c) Either", "(d) Neither"] },
      { id: "Q48", question: "Statement: All species of plants and animals are part of biodiversity and ecosystems.\nAssumptions: I. Preserve or create a backyard habitat. II. One of the major goals of sustainability is to preserve biodiversity.", options: ["(a) Neither", "(b) Both", "(c) Only I", "(d) Only II"] },
      { id: "Q49", question: "Statement: ICMR warning on antibiotic resistance in 50% of hospital patients.\nCourses of Action: I. WHO revision of antibiotic classes is welcome. II. Close scrutiny by national stewardship programmes needed.", options: ["(a) Only I", "(b) Both I and II", "(c) Either I or II", "(d) Only II"] },
      { id: "Q50", question: "Sampada Apartment flat allocation: Qureshi gets North facing, Sawant & Usman diagonally opposite, Rathor South facing next to Usman, Tripathy North facing. Which professors get South facing flats?", options: ["(a) Qureshi, Tripathy, Sawant", "(b) Usman, Tripathy, Purohit", "(c) Usman, Rathor, Purohit", "(d) None of the above"] },
      { id: "Q51", question: "Using same arrangement as Q50, if flats of Tripathy and Purohit are interchanged, whose flat will be next to Usman?", options: ["(a) Prof. Rathor", "(b) Prof. Tripathy", "(c) Prof. Usman", "(d) None of the above"] },
      { id: "Q52", question: "Probable cause for drop in four-wheeler sales over 6 months:\n(A) Higher excise duty imposed early this year.\n(B) Petrol prices rose over past 8 months.\n(C) Interest rate on loans rising past 7 months.", options: ["(a) All (A), (B) and (C)", "(b) (A) and (C) Only", "(c) (B) and (C) Only", "(d) (B) Only"] },
      { id: "Q53", question: "Water image of given figure:", options: ["(a) D", "(b) C", "(c) A", "(d) B"] },
      { id: "Q54", question: "Statement: Government decided to construct 8-lane super highway across state. Implicit Assumption:", options: ["(a) Govt has adequate resources for construction.", "(b) People may protest against farmland acquisition.", "(c) Govt may find it difficult to enroll suitable contractor.", "(d) No other highway exists."] },
      { id: "Q55", question: "Farmers protesting demanding higher MSP and loan waivers. Courses of action:\n(i) Punish protesters.\n(ii) Use cloud seeding.\n(iii) Constitute team to assess drought severity and pay compensation.", options: ["(a) Only (i)", "(b) Both (i) and (ii)", "(c) Only (iii)", "(d) Both (ii) and (iii)"] },
      { id: "Q56", question: "Amir, Sahil, Vaibhav, Gaurav work 24h duty rotations. Gaurav was on duty 10th July 2020, who is on duty 26th September 2020?", options: ["(a) Amir", "(b) Sahil", "(c) Vaibhav", "(d) Gaurav"] },
      { id: "Q57", question: "Sahil was on duty 14th Feb 2020, who did maximum duties in that month?", options: ["(a) Amir", "(b) Sahil", "(c) Vaibhav", "(d) Gaurav"] },
      { id: "Q58", question: "Effect: Temple wears deserted look with decreasing devotees. Possible cause:", options: ["(a) Engineer declared structure unsafe a month back.", "(b) Temple faces depletion of funds.", "(c) Local corp donated huge money for renovation.", "(d) Village has qualified priests."] },
      { id: "Q59", question: "5th, 24th, 16th alphabets + AND = EXPAND. Suffix of 19th, 8th, 18th (SHR) having opposite meaning:", options: ["(a) ACT", "(b) AND", "(c) INK", "(d) NAL"] },
      { id: "Q60", question: "Suffix for 3rd, 15th, 14th, 20th, 18th (CONTR) having same meaning as above:", options: ["(a) ACT", "(b) AND", "(c) INK", "(d) NAL"] }
    ]
  },
  "2022": {
    "General English": [
      { id: "Q1", question: "Which of the following words has a suffix appended to it?", options: ["(a) Frequently", "(b) Often", "(c) Hydrophobia", "(d) Debunk"] },
      { id: "Q2", question: "Fill in the blanks with the appropriate prepositions: The book that has been recently brought _____ provides insight into bringing _____ children.", options: ["(a) up, up", "(b) in, out", "(c) out, up", "(d) down, in"] },
      { id: "Q3", question: "Fill in the blanks with the appropriate conjunction: This can prove to be a difficult task for a leader unfamiliar with building teams _____.", options: ["(a) yet", "(b) not", "(c) until", "(d) but"] },
      { id: "Q4", question: "Given four lines from 'Morituri Salutamus': Line 1: Something remains... Line 2: Even the oldest tree... Line 3: And as the evening... Line 4: The sky is filled... Which follows most standard word order?", options: ["(a) Line 1", "(b) Line 2", "(c) Line 3", "(d) Line 4"] },
      { id: "Q5", question: "Which of the following is a compound word?", options: ["(a) Hold", "(b) Scaffold", "(c) Unsolved", "(d) Threshold"] },
      { id: "Q6", question: "Synonym of underlined word: Ferguson is convincing because of the perspicacity of her observations.", options: ["(a) Clarity", "(b) Cleverness", "(c) Accuracy", "(d) Acuity"] },
      { id: "Q7", question: "Fill in the blank: My mother worked _____ despite her fluctuating health condition.", options: ["(a) tiresome", "(b) tiring", "(c) tirelessly", "(d) tired"] },
      { id: "Q8", question: "Meaning of idiom: 'in the teeth of cynicism'", options: ["(a) stiff opposition", "(b) indifference", "(c) having humour", "(d) appreciation"] },
      { id: "Q9", question: "Convert to Past Perfect: 'People think that globalization is a recent phenomenon.'", options: ["(a) People thought that globalization was a recent phenomenon.", "(b) People had thought that globalization has been a recent phenomenon.", "(c) People were thinking that globalization was a recent phenomenon.", "(d) People have been thinking that globalization will be a recent phenomenon."] },
      { id: "Q10", question: "Change voice: 'By the time you reach auditorium, the pianist would have finished the rendition.'", options: ["(a) By the time auditorium is reached by you, the pianist would have finished to rendition.", "(b) By the time you reach auditorium, the rendition would have finished the pianist.", "(c) By the time auditorium is reached by you, the pianist will have finished the rendition.", "(d) By the time you reach auditorium, the rendition would have been finished by the pianist."] },
      { id: "Q11", question: "Fill in blanks: The wound of the _____ takes much time to _____.", options: ["(a) heal, heel", "(b) heel, hail", "(c) heel, hall", "(d) heel, heal"] },
      { id: "Q12", question: "Which line uses a modal verb seeking approval? Line 1: May I come in, Sir? Line 2: Yes, please have a seat. Line 3: Sir, I could not finish... Line 4: But you ought to stick...", options: ["(a) Line 1", "(b) Line 2", "(c) Line 3", "(d) Line 4"] },
      { id: "Q13", question: "Fill in blank: _____, please find the cheque enclosed.", options: ["(a) On date", "(b) According", "(c) As per the rules", "(d) Accordance"] },
      { id: "Q14", question: "Fill in blank: There is nothing as refreshing as _____ sleep.", options: ["(a) long", "(b) lengthy", "(c) deep", "(d) short"] },
      { id: "Q15", question: "Meaning of proverb: 'A new broom sweeps clean.'", options: ["(a) Old brooms are useless.", "(b) We should frequently buy new brooms.", "(c) Cleanliness is essential to our well being.", "(d) A newly appointed person takes actions that are noticeable."] }
    ],
    "Quantitative & Data Interpretation": [
      { id: "Q16", question: "In a political survey 78% of the politicians favour at least one proposal. 50% are in favour of A, 30% B, 20% C. 5% favour all three. % favouring more than 1 proposal?", options: ["(a) 17", "(b) 18", "(c) 16", "(d) None of these"] },
      { id: "Q17", question: "Rohan sells two pens at Rs 2580 and Rs 1620. Profit % in 1st equals loss % in 2nd. Selling price for 25% final profit?", options: ["(a) 2100 each", "(b) None of these", "(c) 1800 each", "(d) 2625 each"] },
      { id: "Q18", question: "4-digit numbers formed using 1-7 without repetition. How many > 3400?", options: ["(a) 560", "(b) 580", "(c) 540", "(d) None of these"] },
      { id: "Q19", question: "20 people >=45 yrs, at most 26 people <45 yrs. Overall avg age is 32. Largest possible avg age of people <45 yrs?", options: ["(a) 22", "(b) 20", "(c) 21", "(d) None of these"] },
      { id: "Q20", question: "Train travels 150 km, meets accident, proceeds at 3/5th speed, arrives 8 hrs late. Had accident been 360 km farther, arrives 4 hrs late. Total distance?", options: ["(a) 780", "(b) 880", "(c) 720", "(d) None of these"] },
      { id: "Q21", question: "If cos(θ) = 1/2, what will be 6*cot²(θ) - 1?", options: ["(a) 1", "(b) 2", "(c) 0.5", "(d) None of these"] },
      { id: "Q22", question: "Initial male:female ratio is 4:1. At 1st stop 16 male and 8 female get down, 12 female board. New ratio is 8:3. Initial total passengers?", options: ["(a) 100", "(b) 110", "(c) 90", "(d) None of these"] },
      { id: "Q23", question: "Complete series: 0.236, 0.449, 0.645, _____, 1, 1.165", options: ["(a) 0.684", "(b) 0.724", "(c) 0.987", "(d) 0.828"] },
      { id: "Q24", question: "37.5% of a + 41(2/3)% of b = 22. If 37.5% of a exceeds 41(2/3)% of b by 2, find a & b.", options: ["(a) 32, 18", "(b) 36, 12", "(c) 32, 24", "(d) -34, 14"] },
      { id: "Q25", question: "Right △ACB, ∠ACB=90°, CD⊥AB. AC=15cm, BC=20cm. P & Q incenters of △ADC and △BDC. Find PQ.", options: ["(a) 7", "(b) 8", "(c) 5", "(d) 20"] },
      { id: "Q26", question: "4 products initial prices equal. Price increases: A: k%, k+1%; B: k+2%, k-1%; C: k+3%, k-2%; D: k+4%, k-3%. Lowest final price?", options: ["(a) B", "(b) C", "(c) D", "(d) None of these"] },
      { id: "Q27", question: "Sumesh avg runs in 4 innings is 50. 5th inning brings avg to 62. 6th inning scores 10 more than 5th, avg of last 5 innings becomes 80. Runs in 1st inning?", options: ["(a) 28", "(b) 26", "(c) 30", "(d) None of these"] },
      { id: "Q28", question: "Buses A, B, C carry 60 people together per trip. A made trips carrying 50 people per trip, then B & C finished. Total 10 trips for 300 people. Trips A alone takes for 150 people?", options: ["(a) 15", "(b) 10", "(c) 30", "(d) None of these"] },
      { id: "Q29", question: "Boy 1 flies kite at 30° with 100m string. Boy 2 flies from 10m roof at 45°. String length for Boy 2 so kites meet?", options: ["(a) 40√2", "(b) 4√10", "(c) 42√2", "(d) 50√2"] },
      { id: "Q30", question: "20 transistors, 4 defective. Choose 2 randomly. Probability at least one is defective?", options: ["(a) 7/19", "(b) 12/19", "(c) 4/19", "(d) None of these"] },
      { id: "Q31", question: "Largest 4-digit number divided by 3, 4, 5 leaving remainders 2, 3, 4 respectively.", options: ["(a) 9999", "(b) 9959", "(c) 9989", "(d) None of these"] },
      { id: "Q32", question: "Tank 150m x 100m, pipe cross-section 2 dm x 1.5 dm, water speed 15 kmph. Hours to fill tank to 3m height?", options: ["(a) 10 hrs", "(b) 50 hrs", "(c) 100 hrs", "(d) None of the Above"] },
      { id: "Q33", question: "6 sweet varieties (28, 189, 119, 77, 161, 112 count). Minimum boxes needed so each box has same variety and quantity?", options: ["(a) 97", "(b) 98", "(c) 99", "(d) None of the above"] },
      { id: "Q34", question: "Difference between white-coloured cars sold in Metro M and H is minimum for which model?", options: ["(a) A", "(b) C", "(c) D", "(d) None of these"] },
      { id: "Q35", question: "Total blue cars of Model E & D in Metro H equals white cars of which model in Metro M?", options: ["(a) B", "(b) F", "(c) C", "(d) A"] }
    ],
    "Analytical & Logical Reasoning": [
      { id: "Q36", question: "Form PROCRASTINATION from ISNRNRTCTIPOAOA. Position sequence:", options: ["(a) 8, 15, 2, 7, 1, 14, 12, 9, 6, 4, 11, 3, 13, 5, 10", "(b) 11, 4, 14, 8, 6, 15, 2, 7, 1, 3, 13, 9, 10, 12, 5", "(c) 3, 13, 9, 10, 12, 5, 15, 11, 4, 1, 8, 6, 14, 2, 7", "(d) 5, 15, 9, 10, 12, 3, 13, 11, 4, 2, 8, 6, 14, 1, 7"] },
      { id: "Q37", question: "4th Friday was 30 Dec 2005. Day on 03-Jan-2010?", options: ["(a) Sunday", "(b) Thursday", "(c) Saturday", "(d) Friday"] },
      { id: "Q38", question: "A^B = A mother B; A-B = A brother B; A%B = A father B; A≠B = A sister B. Expression where Peach is maternal uncle of Jackfruit?", options: ["(a) Jackfruit-Narangi^Melon Peach", "(b) P^Santara≠N-J", "(c) P-M^N≠J", "(d) J-S%P"] },
      { id: "Q39", question: "Truth-teller/liar/alternator puzzle with Amar, Akbar, Anthony. Who carries gloves?", options: ["(a) Amar", "(b) Anthony", "(c) Data insufficient", "(d) Akbar"] },
      { id: "Q40", question: "Clock starts at 12:00:00 am. At 05:10:00 am, angle formed by hour hand?", options: ["(a) 150°", "(b) 155°", "(c) 157.5°", "(d) 152°"] },
      { id: "Q41", question: "If ab = 3, de = 27 and 7 · dc = 3, then ab : dc :: de : ?", options: ["(a) 9168", "(b) 38691", "(c) 729", "(d) 19683"] },
      { id: "Q42", question: "If BREAKTHROUGH is coded as EAOUHRBRGHKT, CONTRIBUTION is coded as:", options: ["(a) None", "(b) NTTIBUONRICO", "(c) NTTIBUCORION", "(d) NTTIBUCOONRI"] },
      { id: "Q43", question: "Atharva is son of Nannu who is sister of my mother-in-law's daughter. Nonu is my only son. Which is INCORRECT?", options: ["(a) My wife is Nonu's mother.", "(b) Atharva and Nonu's mothers are not real sisters.", "(c) Nonu's mother's mother is mother of my father's only daughter-in-law.", "(d) My mother-in-law's only daughter is Nonu's mother."] },
      { id: "Q44", question: "Pattern: AC(CBABAB), ABC(CABAB), ABAC(CBAB), ABABC(CAB), ABABAC(CB), _____", options: ["(a) CAB, ABABAC(CB", "(b) ABABABC(C", "(c) BABAC(CBA", "(d) BAABC(CAB"] },
      { id: "Q45", question: "Figure matrix continuation with arrow rotations across 3 rows.", options: ["(a) Down-right arrow", "(b) Up arrow", "(c) Left arrow", "(d) Right arrow"] },
      { id: "Q46", question: "Missing number: 27, 22, 18, _____, 8, 3", options: ["(a) 14", "(b) 11", "(c) 15", "(d) 13"] },
      { id: "Q47", question: "Which dates in March 2008 fall on Sunday?", options: ["(a) 3, 10, 17, 24, 31", "(b) 1, 8, 15, 22, 29", "(c) 2, 9, 16, 23, 30", "(d) 7, 14, 21, 28"] },
      { id: "Q48", question: "7 candidates in dresses in line. Direction of point R with respect to candidate E?", options: ["(a) North-East", "(b) South-West", "(c) South-East", "(d) South"] },
      { id: "Q49", question: "Using same arrangement as Q48, position of F with respect to A?", options: ["(a) Immediate Right", "(b) Immediate Left", "(c) Second to the Right", "(d) Second to the Left"] },
      { id: "Q50", question: "Arrange alphabets in words alphabetically, take 3rd letters, select set where meaningful word is NOT formed:", options: ["(a) FTEID, MESAT, OCLKP, GSIUD", "(b) UGJYL, WTUZ, GERNC, PDOFV", "(c) USVH, NDPMH, ETCNB, ITSD", "(d) QHFWA, MBNRH, SEVJ, TKXGU"] },
      { id: "Q51", question: "Input: 7925, 4758, 2538, 5628, 8561, 7426, 3625, 6245. Sum of numbers 2nd, 4th, 6th, 8th from left in step IV?", options: ["(a) 32", "(b) 23", "(c) 38", "(d) 40"] },
      { id: "Q52", question: "TOMATO : MTOOTA :: 123412 : ?", options: ["(a) 312214", "(b) 123456", "(c) 321124", "(d) 213314"] },
      { id: "Q53", question: "Missing value: P-G-22, F-N-21, 27-K-15, E-J-2", options: ["(a) M", "(b) P", "(c) 32", "(d) None of these"] },
      { id: "Q54", question: "Complete pattern matrix response.", options: ["(a) Option A", "(b) Option B", "(c) Option C", "(d) Option D"] },
      { id: "Q55", question: "Meaningful life stage order: 1. Adult, 2. Old age, 3. Adolescent, 4. Childhood, 5. Infant", options: ["(a) 5, 4, 3, 1, 2", "(b) 1, 5, 4, 3, 2", "(c) 1, 2, 3, 4, 5", "(d) 3, 4, 5, 1, 2"] },
      { id: "Q56", question: "Statement: 'Please prepare and send documents to accountant.' Assumptions: I. Assistant follows instruction. II. Handed over personally.", options: ["(a) Both I and II are implicit", "(b) Neither I nor II is implicit", "(c) Only II is implicit", "(d) Only I is implicit"] },
      { id: "Q57", question: "Campaign to abolish dowry. Is it sufficient to eliminate custom?", options: ["(a) Yes, state-wide impact.", "(b) No, requires mindset change & strict penal law.", "(c) Yes, NGO support.", "(d) No, ingrained in social norms."] },
      { id: "Q58", question: "Cause: Govt increased petrol/diesel tax by 10%. Possible effect:", options: ["(a) Companies reduce price 10%", "(b) Companies increase price 10%", "(c) Companies increase price 5%", "(d) Pumps stop selling"] },
      { id: "Q59", question: "Statement: Politics study should be compulsory in school. Arguments: I. Informed electorate builds democracy. II. Affects education quality.", options: ["(a) If only argument I is strong", "(b) If only argument II is strong", "(c) If either I or II is strong", "(d) If neither I nor II is strong"] },
      { id: "Q60", question: "Family tree puzzle (8 members, 3 couples). Who is sister of H?", options: ["(a) K", "(b) M", "(c) G", "(d) P"] }
    ]
  }
};